# Generated by Django 5.2.4 on 2025-07-18 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_details', to='ResumeApp.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('basic_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_sections', to='ResumeApp.basic_details')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('basic_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='ResumeApp.basic_details')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('issuing_organization', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('basic_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='ResumeApp.basic_details')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('gpa', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.TextField()),
                ('end_date', models.TextField()),
                ('description', models.TextField()),
                ('basic_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='ResumeApp.basic_details')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=100)),
                ('start_date', models.TextField()),
                ('end_date', models.TextField()),
                ('currently_working', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('basic_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='ResumeApp.basic_details')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technologies_used', models.JSONField(blank=True, default=list)),
                ('start_date', models.TextField()),
                ('end_date', models.TextField()),
                ('ongoing', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, null=True)),
                ('basic_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='ResumeApp.basic_details')),
            ],
        ),
    ]
